# Generated by Django 3.0.1 on 2019-12-27 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30, verbose_name='昵称')),
                ('birday', models.DateField(null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('', '男'), ('female', '女')], default='female', max_length=6)),
                ('address', models.CharField(default='', max_length=100, verbose_name='家地址')),
                ('mobile', models.CharField(default='', max_length=11, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用积分')),
                ('status', models.CharField(choices=[(0, '待审核'), (2, '吊销'), (1, '正常')], default=0, max_length=11, null=True, verbose_name='司机状态')),
                ('company', models.CharField(default='', max_length=100, verbose_name='公司地址')),
                ('department', models.CharField(default='', max_length=100, verbose_name='部门')),
                ('money', models.CharField(default='', max_length=100, verbose_name='余额')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '司机信息',
                'verbose_name_plural': '司机信息',
            },
        ),
        migrations.CreateModel(
            name='ExamineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=30, verbose_name='申请人')),
                ('gender', models.CharField(choices=[('', '男'), ('female', '女')], default='female', max_length=6)),
                ('age', models.CharField(max_length=6)),
                ('address', models.CharField(default='', max_length=100, verbose_name='住址')),
                ('mobile', models.CharField(default='', max_length=11, null=True)),
                ('license', models.ImageField(upload_to='', verbose_name='驾照')),
                ('status', models.CharField(choices=[(0, '待审核'), (2, '未通过'), (1, '通过')], default=0, max_length=11, null=True, verbose_name='审核状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
            },
        ),
        migrations.CreateModel(
            name='FoulRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=6, verbose_name='简称')),
                ('msg', models.CharField(default='', max_length=6, verbose_name='条目注释')),
                ('deduction', models.IntegerField(default=0, verbose_name='扣分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '司机违规条目',
                'verbose_name_plural': '司机违规条目',
            },
        ),
    ]
