# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='信息内容', max_length=500, verbose_name='信息内容')),
                ('has_read', models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default='未读', help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统信息推送司机',
                'verbose_name_plural': '系统信息推送司机',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='老司机', max_length=30, verbose_name='昵称')),
                ('birday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女')], default='男', help_text='性别 0/1 - 男/女', max_length=6)),
                ('address', models.CharField(blank=True, default='固戍A口', max_length=100, verbose_name='家地址')),
                ('mobile', models.CharField(blank=True, default='1316xxxx2644', max_length=11, null=True)),
                ('image', models.ImageField(blank=True, default='examine/images/default.png', upload_to='examine/image/%Y%m%d')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用积分')),
                ('status', models.CharField(choices=[(0, '待审核'), (2, '吊销'), (1, '正常')], default='待审核', max_length=11, null=True, verbose_name='司机状态')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='公司名称')),
                ('company_address', models.CharField(blank=True, default='', max_length=100, verbose_name='公司地址')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='部门')),
                ('money', models.CharField(default=0, max_length=100, verbose_name='余额')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '司机信息',
                'verbose_name_plural': '司机信息',
            },
        ),
        migrations.CreateModel(
            name='ExamineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ImageField(blank=True, default='', upload_to='', verbose_name='驾照')),
                ('f_id_card', models.ImageField(blank=True, default='', upload_to='', verbose_name='身份证正面照')),
                ('b_id_card', models.ImageField(blank=True, default='', upload_to='', verbose_name='身份证背面照')),
                ('f_car', models.ImageField(blank=True, default='', upload_to='', verbose_name='车正面照')),
                ('l_car', models.ImageField(blank=True, default='', upload_to='', verbose_name='车左侧照')),
                ('r_car', models.ImageField(blank=True, default='', upload_to='', verbose_name='车右侧照')),
                ('status', models.CharField(choices=[(0, '待审核'), (2, '未通过'), (1, '通过')], default=0, max_length=30, null=True, verbose_name='审核状态 0/1/2 - 待审核/通过/未通过')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('applicant', models.ForeignKey(help_text='司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机 id')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
            },
        ),
        migrations.CreateModel(
            name='FoulLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('applicant', models.ForeignKey(help_text='违规人 -  司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='违规人 - 司机 id')),
            ],
            options={
                'verbose_name': '违规记录',
                'verbose_name_plural': '违规记录',
            },
        ),
        migrations.CreateModel(
            name='FoulRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=6, verbose_name='简称')),
                ('msg', models.CharField(blank=True, default='', max_length=6, verbose_name='条目注释')),
                ('deduction', models.IntegerField(default=0, verbose_name='扣分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '司机违规条目',
                'verbose_name_plural': '司机违规条目',
            },
        ),
        migrations.AddField(
            model_name='foullog',
            name='foul_rule',
            field=models.ForeignKey(help_text='违规条目 id', on_delete=django.db.models.deletion.CASCADE, to='examine.FoulRule', verbose_name='违规条目 id'),
        ),
        migrations.AddField(
            model_name='drivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人 司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='接收人'),
        ),
    ]
