# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-16 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='drivermessage',
            name='receiver',
            field=models.ForeignKey(help_text='接收人 司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='接收人'),
        ),
    ]
