# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='money',
            new_name='driver_money',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='credit_score',
            new_name='driver_score',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='status',
            new_name='driver_status',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='birday',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
