# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0002_auto_20200116_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_name',
            field=models.CharField(default='帅司机', max_length=50, verbose_name='司机名'),
        ),
    ]
