# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0002_auto_20191229_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermessage',
            name='has_read',
            field=models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default=0, help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_status',
            field=models.CharField(choices=[(0, '待审核'), (2, '吊销'), (1, '正常')], default=0, max_length=11, null=True, verbose_name='司机状态'),
        ),
    ]
