# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.CharField(choices=[(1, '顾客'), (2, '司机')], help_text='取消者  1/2 - 顾客/司机', max_length=50)),
                ('punish', models.CharField(blank=True, default='', help_text='取消备注留言', max_length=50)),
                ('overtime', models.CharField(blank=True, default='00:02', help_text='下单后时长, 格式: 00:20 ', max_length=50, verbose_name='下单后时长')),
                ('deduction', models.CharField(blank=True, default=5, help_text='扣分值', max_length=50, verbose_name='扣分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行程订单',
                'verbose_name_plural': '行程订单',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='信息内容', max_length=500, verbose_name='信息内容')),
                ('has_read', models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default='未读', help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(blank=True, default=0, help_text='星级 1-5', verbose_name='星级')),
                ('c_label', models.CharField(choices=[(1, '好评'), (2, '差评')], default='好评', help_text='评论类别 1:好评, 2:差评 默认 好评', max_length=30, verbose_name='评论类别')),
                ('comments', models.CharField(blank=True, default='', help_text='评论内容', max_length=200, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行程评价',
                'verbose_name_plural': '行程评价',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='信息内容', max_length=500, verbose_name='信息内容')),
                ('has_read', models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default='未读', help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统信息推送顾客',
                'verbose_name_plural': '系统信息推送顾客',
            },
        ),
        migrations.CreateModel(
            name='DriverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='信息内容', max_length=500, verbose_name='信息内容')),
                ('has_read', models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default='未读', help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('receiver', models.ForeignKey(help_text='接收人 司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='接收人')),
            ],
            options={
                'verbose_name': '系统信息推送司机',
                'verbose_name_plural': '系统信息推送司机',
            },
        ),
        migrations.CreateModel(
            name='FoulLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('applicant', models.ForeignKey(help_text='违规人 -  司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='违规人 - 司机 id')),
                ('foul_rule', models.ForeignKey(help_text='违规条目 id', on_delete=django.db.models.deletion.CASCADE, to='examine.FoulRule', verbose_name='违规条目 id')),
            ],
            options={
                'verbose_name': '违规记录',
                'verbose_name_plural': '违规记录',
            },
        ),
    ]
