# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drakbill',
            name='trade_no',
            field=models.ForeignKey(help_text='交易号', on_delete=django.db.models.deletion.CASCADE, to='order.Order', to_field='trade_no', verbose_name='交易号'),
        ),
    ]
