# Generated by Django 3.0.1 on 2019-12-28 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191228_1317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examine', '0002_auto_20191228_1317'),
        ('operation', '0002_auto_20191227_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemMessage',
            new_name='CustomerMessage',
        ),
        migrations.AlterModelOptions(
            name='customermessage',
            options={'verbose_name': '系统信息推送顾客', 'verbose_name_plural': '系统信息推送顾客'},
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='c_label',
            field=models.CharField(choices=[(1, '好评'), (2, '差评')], default=1, max_length=200, verbose_name='评论类别'),
        ),
        migrations.CreateModel(
            name='DriverMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='信息内容')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='接收人')),
            ],
            options={
                'verbose_name': '系统信息推送司机',
                'verbose_name_plural': '系统信息推送司机',
            },
        ),
        migrations.CreateModel(
            name='CancelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.CharField(choices=[(1, '顾客'), (2, '司机')], max_length=50)),
                ('punish', models.CharField(max_length=50)),
                ('overtime', models.CharField(max_length=50, verbose_name='超时时长')),
                ('deduction', models.CharField(max_length=50, verbose_name='扣分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '行程订单',
                'verbose_name_plural': '行程订单',
            },
        ),
    ]
