# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 18:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(default='阿一', help_text='昵称', max_length=50, verbose_name='昵称')),
                ('birday', models.DateField(help_text='生日', null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女')], default='男', help_text='性别  0/1 - 男/女', max_length=6, verbose_name='性别')),
                ('address', models.CharField(blank=True, default='', help_text='地址', max_length=100)),
                ('mobile', models.CharField(default='1316XXXX1236', help_text='电话', max_length=11)),
                ('image', models.ImageField(default='users/images/default.png', help_text='头像', upload_to='users/images/%Y%m%d', verbose_name='头像')),
                ('home', models.CharField(blank=True, default='', help_text='家地址', max_length=100, verbose_name='家地址')),
                ('company_address', models.CharField(blank=True, default='', help_text='公司地址', max_length=100, verbose_name='公司地址')),
                ('company', models.CharField(blank=True, default='', help_text='公司名称', max_length=100, verbose_name='公司名称')),
                ('department', models.CharField(blank=True, default='', help_text='部门', max_length=100, verbose_name='部门')),
                ('credit_score', models.IntegerField(default=100, help_text='信用积分', verbose_name='信用积分')),
                ('money', models.CharField(default=0, help_text='余额', max_length=100, verbose_name='余额')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(help_text='卡号', max_length=200, verbose_name='卡号')),
                ('bank', models.URLField(blank=True, help_text='所属银行', null=True, verbose_name='所属银行')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(help_text='用户 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户 id')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, null=True, verbose_name='标题')),
                ('image', models.ImageField(help_text='轮播图', max_length=200, upload_to='users/images/%Y%m%d', verbose_name='轮播图')),
                ('url', models.URLField(blank=True, help_text='访问地址', null=True, verbose_name='访问地址')),
                ('index', models.IntegerField(default=1, help_text='顺序', verbose_name='顺序')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='信息内容', max_length=500, verbose_name='信息内容')),
                ('has_read', models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default='未读', help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('receiver', models.ForeignKey(help_text='接收人 - 顾客 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '系统信息推送顾客',
                'verbose_name_plural': '系统信息推送顾客',
            },
        ),
    ]
