# Generated by Django 3.0.1 on 2019-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=100, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.CharField(default='', max_length=100, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', '男'), ('female', '女')], default='female', max_length=6),
        ),
    ]
