# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_driver',
            field=models.CharField(choices=[(0, '否'), (1, '是')], default='否', help_text='是否司机', max_length=100, verbose_name='是否司机'),
        ),
    ]
