# Generated by Django 3.0.1 on 2019-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191227_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_score',
            field=models.IntegerField(default=100, verbose_name='信用积分'),
        ),
    ]
