# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200105_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='15681234566', help_text='电话', max_length=11),
        ),
    ]
