# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-29 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200129_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
