# Generated by Django 3.0.1 on 2019-12-27 20:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.CharField(max_length=200, verbose_name='里程')),
                ('take_time', models.CharField(max_length=200, verbose_name='耗时')),
                ('Amount', models.CharField(max_length=200, verbose_name='金额')),
                ('status', models.CharField(max_length=200, verbose_name='订单状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机')),
            ],
            options={
                'verbose_name': '行程订单',
                'verbose_name_plural': '行程订单',
            },
        ),
    ]
