# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, default='', help_text='起点', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(blank=True, default='', help_text='终点', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(blank=True, default='', help_text='备注', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(blank=True, default='', help_text='预测金额', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, help_text='乘坐人数', max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[(1, '已预订'), (0, '待预定')], default='待预定', help_text='订单状态', max_length=30, verbose_name='订单状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default='上班', help_text='出行类别', max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(help_text='出发时间', verbose_name='出发时间')),
                ('add_time', models.DateTimeField(help_text='添加时间', verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='DriverSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, default='', help_text='起点', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(blank=True, default='', help_text='终点', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(blank=True, default='', help_text='备注', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(blank=True, default=30, help_text='预测金额', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, help_text='乘坐人数', max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[(1, '已预订'), (0, '待预定')], default='待预定', help_text='订单状态', max_length=30, verbose_name='订单状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default='上班', help_text='出行类别', max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(help_text='出发起始时间', verbose_name='出发起始时间')),
                ('e_time', models.DateTimeField(help_text='出发截止时间', verbose_name='出发截止时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, help_text='订单号', max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, help_text='交易号', max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='支付时间')),
                ('mileage', models.CharField(blank=True, default='', help_text='里程', max_length=200, verbose_name='里程')),
                ('origin', models.CharField(blank=True, default='', help_text='起点', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(blank=True, default='', help_text='终点', max_length=200, verbose_name='终点')),
                ('take_time', models.CharField(blank=True, default='', help_text='耗时', max_length=200, verbose_name='耗时')),
                ('amount', models.CharField(blank=True, default='', help_text='金额', max_length=200, verbose_name='金额')),
                ('p_num', models.CharField(default=1, help_text='乘坐人数', max_length=200, verbose_name='乘坐人数')),
                ('s_time', models.DateTimeField(blank=True, help_text='出发时间', null=True, verbose_name='出发时间')),
                ('e_time', models.DateTimeField(blank=True, help_text='抵达时间', null=True, verbose_name='抵达时间')),
                ('pay_status', models.CharField(choices=[(1, '成功'), (2, '超时关闭'), (3, '交易创建'), (4, '交易结束'), (0, '待支付')], default='待支付', help_text='订单状态 0/1/2/3/4/5 - 待支付/成功/超时关闭/交易创建/交易结束', max_length=30, verbose_name='订单状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行程订单',
                'verbose_name_plural': '行程订单',
            },
        ),
    ]
