# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-28 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(default='', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(default='', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[('RESERVED', '已预订'), ('RESERVING', '待预定')], default='RESERVING', max_length=30, verbose_name='预定状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='DriverSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(default='', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(default='', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[('RESERVED', '已预订'), ('RESERVING', '待预定')], default='RESERVING', max_length=30, verbose_name='订单状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发起始时间')),
                ('e_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发截止时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('mileage', models.CharField(default='', max_length=200, verbose_name='里程')),
                ('origin', models.CharField(default='', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(default='', max_length=200, verbose_name='终点')),
                ('take_time', models.CharField(default='', max_length=200, verbose_name='耗时')),
                ('amount', models.CharField(default='', max_length=200, verbose_name='金额')),
                ('p_num', models.CharField(default=1, max_length=200, verbose_name='乘坐人数')),
                ('s_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发时间')),
                ('e_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='抵达时间')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=30, verbose_name='订单状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行程订单',
                'verbose_name_plural': '行程订单',
            },
        ),
    ]
