# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-16 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='initiator',
            field=models.ForeignKey(help_text='顾客 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客 id'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='m_order',
            field=models.ForeignKey(help_text='主订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.DriverOrder', verbose_name='主订单 id'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', unique=True, verbose_name='订单 id'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', verbose_name='订单 id'),
        ),
        migrations.AddField(
            model_name='cancellog',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', unique=True, verbose_name='订单'),
        ),
    ]
