# Generated by Django 3.0.1 on 2019-12-28 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0002_auto_20191228_1317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default='', max_length=200, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='e_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='抵达时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.CharField(default='', max_length=200, verbose_name='终点'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(default='', max_length=200, verbose_name='起点'),
        ),
        migrations.AddField(
            model_name='order',
            name='p_num',
            field=models.CharField(default=1, max_length=200, verbose_name='乘坐人数'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='s_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='出发时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mileage',
            field=models.CharField(default='', max_length=200, verbose_name='里程'),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_time',
            field=models.CharField(default='', max_length=200, verbose_name='耗时'),
        ),
        migrations.CreateModel(
            name='DriverSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(default='', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(default='', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[('RESERVED', '已预订'), ('RESERVING', '待预定')], default='RESERVING', max_length=30, verbose_name='订单状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发起始时间')),
                ('e_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发截止时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=200, verbose_name='起点')),
                ('finish', models.CharField(default='', max_length=200, verbose_name='终点')),
                ('remarks', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('mount', models.CharField(default='', max_length=200, verbose_name='预测金额')),
                ('p_num', models.CharField(default=1, max_length=200, verbose_name='乘坐人数')),
                ('r_status', models.CharField(choices=[('RESERVED', '已预订'), ('RESERVING', '待预定')], default='RESERVING', max_length=30, verbose_name='预定状态')),
                ('label_type', models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, max_length=30, verbose_name='出行类别')),
                ('s_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出发时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客')),
            ],
        ),
    ]
