# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-29 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examine', '__first__'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='顾客 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客 id'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(help_text='司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机 id'),
        ),
        migrations.AddField(
            model_name='driversquare',
            name='initiator',
            field=models.ForeignKey(help_text='司机 id', on_delete=django.db.models.deletion.CASCADE, to='examine.DriverProfile', verbose_name='司机'),
        ),
        migrations.AddField(
            model_name='customersquare',
            name='initiator',
            field=models.ForeignKey(help_text='顾客 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='顾客 id'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单 id'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单 id'),
        ),
        migrations.AddField(
            model_name='cancellog',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单'),
        ),
    ]
