# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-16 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200116_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='m_order',
            field=models.ForeignKey(help_text='主订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DriverOrder', verbose_name='主订单 id'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='m_order',
            field=models.ForeignKey(help_text='主订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DriverOrder', verbose_name='主订单 id'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(help_text='子订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', verbose_name='子订单 id'),
        ),
        migrations.AlterField(
            model_name='driverorder',
            name='initiator',
            field=models.ForeignKey(help_text='司机 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='司机 id'),
        ),
    ]
