# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191229_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='has_read',
            field=models.CharField(blank=True, choices=[(1, '已读'), (0, '未读')], default=0, help_text='是否已读 0/1 - 未/已', max_length=30, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[(1, '乘客'), (2, '司机')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='c_label',
            field=models.CharField(choices=[(1, '好评'), (2, '差评')], default=1, help_text='评论类别 1:好评, 2:差评 默认 好评', max_length=30, verbose_name='评论类别'),
        ),
        migrations.AlterField(
            model_name='customersquare',
            name='label_type',
            field=models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, help_text='出行类别', max_length=30, verbose_name='出行类别'),
        ),
        migrations.AlterField(
            model_name='customersquare',
            name='r_status',
            field=models.CharField(choices=[(1, '已预订'), (0, '待预定')], default=0, help_text='订单状态', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='driversquare',
            name='label_type',
            field=models.CharField(choices=[(1, '上班'), (2, '下班')], default=1, help_text='出行类别', max_length=30, verbose_name='出行类别'),
        ),
        migrations.AlterField(
            model_name='driversquare',
            name='r_status',
            field=models.CharField(choices=[(1, '已预订'), (0, '待预定')], default=0, help_text='订单状态', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[(0, '待进行'), (1, '正在进行'), (2, '待支付'), (3, '交易创建'), (4, '交易结束'), (5, '超时关闭')], default=0, help_text='订单状态 0/1/2/3/4/5 - 待进行/正在进行/待支付/交易创建/交易结束/超时关闭', max_length=30, verbose_name='订单状态'),
        ),
    ]
