# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200105_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='submitter',
            field=models.CharField(choices=[(1, '乘客'), (2, '司机')], default=1, max_length=30, verbose_name='提交评论角色  1/2 - 乘客/司机'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='cancel',
            field=models.CharField(choices=[(1, '顾客'), (2, '司机')], help_text='取消人角色  1/2 - 顾客/司机', max_length=50),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.Order', unique=True, verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[(1, '乘客'), (2, '司机')], default=1, max_length=30, verbose_name='发送人角色 1/2 - 乘客/司机'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='order',
            field=models.ForeignKey(help_text='订单 id', on_delete=django.db.models.deletion.CASCADE, to='order.Order', unique=True, verbose_name='订单 id'),
        ),
    ]
