# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-17 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200116_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='m_order',
        ),
    ]
