# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-21 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_auto_20200120_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellog',
            name='cancel',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='submitter',
        ),
        migrations.AddField(
            model_name='cancellog',
            name='is_driver',
            field=models.CharField(choices=[('n', '否'), ('y', '是')], default='n', help_text='是否司机', max_length=100, verbose_name='是否司机'),
        ),
        migrations.AddField(
            model_name='cancellog',
            name='submitter',
            field=models.ForeignKey(help_text='取消人 id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='取消人 id'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='m_order',
            field=models.ForeignKey(help_text='订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DriverOrder', unique=True, verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='order',
            field=models.ForeignKey(help_text='订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', unique=True, verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='star',
            field=models.IntegerField(blank=True, default='5', help_text='星级 1-5', verbose_name='星级'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='r_status',
            field=models.CharField(choices=[('y', '待预定'), ('n', '已预订')], default='y', help_text='订单状态 y/n - 已预订/待预订', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='driverorder',
            name='r_status',
            field=models.CharField(choices=[('y', '待预定'), ('n', '结束预定')], default='y', help_text='订单状态 y/n - 待预定/结束预定', max_length=30, verbose_name='订单状态'),
        ),
    ]
