# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200121_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellog',
            name='m_order',
            field=models.ForeignKey(help_text='订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DriverOrder', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='order',
            field=models.ForeignKey(help_text='订单 id', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerOrder', verbose_name='订单'),
        ),
        migrations.AlterUniqueTogether(
            name='cancellog',
            unique_together=set([('m_order', 'order')]),
        ),
    ]
