# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-30 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200121_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='f_la',
            field=models.CharField(blank=True, default='', help_text='终点-维度', max_length=200, verbose_name='终点-维度'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='f_lo',
            field=models.CharField(blank=True, default='', help_text='终点-经度', max_length=200, verbose_name='终点-经度'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='o_la',
            field=models.CharField(blank=True, default='', help_text='起点-维度', max_length=200, verbose_name='起点-维度'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='o_lo',
            field=models.CharField(blank=True, default='', help_text='起点-经度', max_length=200, verbose_name='起点-经度'),
        ),
        migrations.AddField(
            model_name='driverorder',
            name='f_la',
            field=models.CharField(blank=True, default='', help_text='终点-维度', max_length=200, verbose_name='终点-维度'),
        ),
        migrations.AddField(
            model_name='driverorder',
            name='f_lo',
            field=models.CharField(blank=True, default='', help_text='终点-经度', max_length=200, verbose_name='终点-经度'),
        ),
        migrations.AddField(
            model_name='driverorder',
            name='o_la',
            field=models.CharField(blank=True, default='', help_text='起点-维度', max_length=200, verbose_name='起点-维度'),
        ),
        migrations.AddField(
            model_name='driverorder',
            name='o_lo',
            field=models.CharField(blank=True, default='', help_text='起点-经度', max_length=200, verbose_name='起点-经度'),
        ),
    ]
